### PR TITLE
Bug Fixed | Draw Dialog Appears Two times

### PR DESCRIPTION
**Pull request by TusharSharmaIN**
The bug is fixed, now if the match gets ties, it only appears one time.
Please let me know if it works for you.

### CODE REVIEW

**Comment by voxer03** [comment]
Thanks for the help.
can you tell how you figured it out  .

**Comment by TusharSharmaIN** [comment]
I was testing your code by simply and commenting out some section which appears redundant to me, and luckily I found out the issue.

**Comment by voxer03** [comment]
Great. Thankyou for your contribution

**Comment by TusharSharmaIN** [comment]
Would like to assist you again, please add label hectoberfest to the issue if you can.

**Pull request merged**
